import {
  TrendingUp,
  TrendingDown,
  Zap,
  ListChecks,
  ShieldCheck,
  Gauge,
  Database,
  Star,
  Download,
  WifiOff,
  Layers,
  Palette,
  Activity,
  Heart,
  Fuel,
  Truck,
  MapPin,
  Navigation,
  type LucideIcon,
} from 'lucide-react';

/** Maps a stat's `icon` key to a lucide icon for the case-study Results cards. */
export const statIcons: Record<string, LucideIcon> = {
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  zap: Zap,
  listChecks: ListChecks,
  shieldCheck: ShieldCheck,
  gauge: Gauge,
  database: Database,
  star: Star,
  download: Download,
  wifiOff: WifiOff,
  layers: Layers,
  palette: Palette,
  activity: Activity,
  heart: Heart,
  fuel: Fuel,
  truck: Truck,
  mapPin: MapPin,
  navigation: Navigation,
};
