/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Triggers Better Auth password reset flow and sends the customer a reset email from the backend email service.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite an organization member
         * @description Creates a Better Auth organization invitation for the FCOP organization and sends an invitation email. Requires invitation:create permission in the active organization.
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch all leads
         * @description Requires lead:read permission in the active organization.
         */
        get: operations["getLeads"];
        put?: never;
        /**
         * Create a lead
         * @description Creates a lead from an unauthenticated website form submission.
         */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a lead by id
         * @description Requires lead:read permission in the active organization.
         */
        get: operations["getLeadById"];
        /**
         * Update a lead by id
         * @description Requires lead:update permission in the active organization.
         */
        put: operations["updateLeadById"];
        post?: never;
        /**
         * Delete a lead by id
         * @description Requires lead:delete permission in the active organization.
         */
        delete: operations["deleteLeadById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch service requests
         * @description Requires serviceRequest:read permission in the active organization.
         */
        get: operations["getServiceRequests"];
        put?: never;
        /**
         * Create a service request
         * @description Creates a service request for the authenticated client.
         */
        post: operations["createServiceRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a service request by id
         * @description Requires serviceRequest:read permission in the active organization.
         */
        get: operations["getServiceRequestById"];
        /**
         * Update a service request by id
         * @description Requires serviceRequest:update permission in the active organization.
         */
        put: operations["updateServiceRequestById"];
        post?: never;
        /**
         * Delete a service request by id
         * @description Requires serviceRequest:delete permission in the active organization.
         */
        delete: operations["deleteServiceRequestById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example NEW
         * @enum {string}
         */
        LeadStatus: "NEW" | "IN_PROGRESS" | "DEAD";
        /**
         * @example CONTACT_FORM
         * @enum {string}
         */
        LeadSource: "CONTACT_FORM";
        /**
         * @example WEB_DEVELOPMENT
         * @enum {string}
         */
        ServiceInterest: "GOOGLE_ADS" | "SEO" | "WEB_DEVELOPMENT" | "MOBILE_APP_DEVELOPMENT" | "GENERAL_MARKETING" | "OTHER";
        /**
         * @example NEW
         * @enum {string}
         */
        ServiceRequestStatus: "NEW" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        ApiResponse: {
            /** @example true */
            success: boolean;
            /** @example 200 */
            status: number;
            /** @example Health check passed. */
            message: string;
            data?: unknown;
            error?: {
                /** @example NOT_FOUND */
                code: string;
                details?: string;
            };
        };
        User: {
            /** @example clx0000000000000000000000 */
            id: string;
            /** @example Akshay */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example true */
            emailVerified: boolean;
            /** @example https://example.com/avatar.png */
            image?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Session: {
            /** @example clx0000000000000000000001 */
            id: string;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            expiresAt: string;
            /** @example session-token */
            token: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
            /** @example 127.0.0.1 */
            ipAddress?: string | null;
            /** @example Mozilla/5.0 */
            userAgent?: string | null;
            /** @example clx0000000000000000000000 */
            userId: string;
        };
        Account: {
            /** @example clx0000000000000000000002 */
            id: string;
            /** @example akshay@example.com */
            accountId: string;
            /** @example credential */
            providerId: string;
            /** @example clx0000000000000000000000 */
            userId: string;
            accessToken?: string | null;
            refreshToken?: string | null;
            idToken?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            accessTokenExpiresAt?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            refreshTokenExpiresAt?: string | null;
            /** @example openid email profile */
            scope?: string | null;
            password?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Verification: {
            /** @example clx0000000000000000000003 */
            id: string;
            /** @example akshay@example.com */
            identifier: string;
            /** @example verification-token */
            value: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:45:00.000Z
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Lead: {
            /** @example clx0000000000000000000004 */
            id: string;
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status: components["schemas"]["LeadStatus"];
            source: components["schemas"]["LeadSource"];
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        CreateLeadRequest: {
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
        };
        UpdateLeadRequest: {
            /** @example Akshay Kumar */
            name?: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email?: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest?: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status?: components["schemas"]["LeadStatus"];
        };
        /**
         * @description Service-specific answers collected from the selected service template.
         * @example {
         *       "websiteUrl": "https://example.com",
         *       "targetKeywords": [
         *         "seo agency",
         *         "web development"
         *       ]
         *     }
         */
        ServiceRequestData: {
            [key: string]: unknown;
        };
        ServiceRequest: {
            /** @example clx0000000000000000000006 */
            id: string;
            /** @example clx0000000000000000000005 */
            clientId: string;
            service: components["schemas"]["ServiceInterest"];
            status: components["schemas"]["ServiceRequestStatus"];
            data?: components["schemas"]["ServiceRequestData"] | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        CreateServiceRequestRequest: {
            service: components["schemas"]["ServiceInterest"];
            data?: components["schemas"]["ServiceRequestData"];
        };
        UpdateServiceRequestRequest: {
            status?: components["schemas"]["ServiceRequestStatus"];
            data?: components["schemas"]["ServiceRequestData"];
        };
        RequestPasswordResetRequest: {
            /**
             * Format: email
             * @example customer@example.com
             */
            email: string;
            /**
             * Format: uri
             * @description Optional frontend reset password page. Origin must be configured as a trusted frontend origin.
             * @example http://localhost:3000/reset-password
             */
            redirectTo?: string;
        };
        RequestPasswordResetResponse: components["schemas"]["ApiResponse"] & {
            /** @example null */
            data?: unknown;
            /** @example If an account exists for this email, a password reset link has been sent. */
            message?: string;
        };
        /**
         * @example CLIENT
         * @enum {string}
         */
        InviteMemberRole: "MANAGER" | "MEMBER" | "CLIENT";
        InviteMemberRequest: {
            /**
             * Format: email
             * @example client@example.com
             */
            email: string;
            role: components["schemas"]["InviteMemberRole"];
            /**
             * @description Resend the invitation email if a pending invitation already exists.
             * @example true
             */
            resend?: boolean;
        };
        Invitation: {
            /** @example clx0000000000000000000005 */
            id: string;
            /**
             * Format: email
             * @example client@example.com
             */
            email: string;
            /** @example CLIENT */
            role: string;
            /** @example seed-org-fanatic-coders */
            organizationId: string;
            /** @example seed-user-admin */
            inviterId: string;
            /** @example pending */
            status: string;
            /**
             * Format: date-time
             * @example 2026-07-08T06:30:00.000Z
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            createdAt?: string;
        };
        InvitationResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Invitation"];
        };
        LeadsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Lead"][];
        };
        LeadResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Lead"];
        };
        ServiceRequestsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["ServiceRequest"][];
        };
        ServiceRequestResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["ServiceRequest"];
        };
        HealthResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["HealthData"];
        };
        HealthData: {
            /** @example ok */
            status: string;
            /** @example 42.5 */
            uptime: number;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description Authenticated user does not have the required permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        /** @example clx0000000000000000000004 */
        LeadId: string;
        /** @example clx0000000000000000000006 */
        ServiceRequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Request accepted. The response does not reveal whether the email exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPasswordResetResponse"];
                };
            };
            /** @description Invalid email or redirect URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Invitation created and invitation email queued/sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Invalid invitation payload or Better Auth rejected the invitation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description FCOP organization has not been bootstrapped. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getLeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leads fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description Lead captured successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadRequest"];
            };
        };
        responses: {
            /** @description Lead updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getServiceRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service requests fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createServiceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceRequestRequest"];
            };
        };
        responses: {
            /** @description Service request created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Invalid service request payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Client profile has not been created. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service request fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceRequestRequest"];
            };
        };
        responses: {
            /** @description Service request updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Invalid service request payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service request deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
