/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch payments
         * @description Admin and Manager receive organization payment history. Client receives only payments for their own service requests.
         */
        get: operations["getPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch admin dashboard overview */
        get: operations["getAdminDashboardOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch admin lead status distribution */
        get: operations["getAdminDashboardLeadDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch admin task status distribution */
        get: operations["getAdminDashboardTaskDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/recent/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch recent admin dashboard leads */
        get: operations["getAdminDashboardRecentLeads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/attention/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch admin dashboard attention tasks */
        get: operations["getAdminDashboardAttentionTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch current member notifications */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all current member notifications as read */
        patch: operations["markAllNotificationsAsRead"];
        trace?: never;
    };
    "/api/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark one current member notification as read */
        patch: operations["markNotificationAsRead"];
        trace?: never;
    };
    "/api/v1/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Triggers Better Auth password reset flow and sends the customer a reset email from the backend email service.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch current user access
         * @description Returns the authenticated user, active organization member, role, and permission statements for UI access checks.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite an organization member
         * @description Creates a Better Auth organization invitation for the FCOP organization and sends an invitation email. Requires invitation:create permission in the active organization.
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch all leads
         * @description Requires lead:read permission in the active organization.
         */
        get: operations["getLeads"];
        put?: never;
        /**
         * Create a lead
         * @description Accepts an unauthenticated website enquiry. New contacts become leads; existing clients receive an email directing them to the authenticated service request flow.
         */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a lead by id
         * @description Requires lead:read permission in the active organization.
         */
        get: operations["getLeadById"];
        /**
         * Update a lead by id
         * @description Requires lead:update permission in the active organization.
         */
        put: operations["updateLeadById"];
        post?: never;
        /**
         * Delete a lead by id
         * @description Requires lead:delete permission in the active organization.
         */
        delete: operations["deleteLeadById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch service requests
         * @description Requires serviceRequest:read permission in the active organization.
         */
        get: operations["getServiceRequests"];
        put?: never;
        /**
         * Create a service request
         * @description Creates a service request for the authenticated client.
         */
        post: operations["createServiceRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-requests/{serviceRequestId}/proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a proposal
         * @description Returns the proposal for a service request. Clients can access only their own service request.
         */
        get: operations["getServiceRequestProposal"];
        put?: never;
        /**
         * Create a proposal
         * @description Creates the single draft proposal for a service request. Available to Admin and Manager roles.
         */
        post: operations["createServiceRequestProposal"];
        /**
         * Delete a proposal
         * @description Deletes a draft or sent proposal. Accepted proposals are preserved as immutable records.
         */
        delete: operations["deleteServiceRequestProposal"];
        options?: never;
        head?: never;
        /**
         * Update a proposal
         * @description Admin and Manager can change draft terms or set status to SENT. The owning Client can only set status to ACCEPTED. Accepted proposals are immutable.
         */
        patch: operations["updateServiceRequestProposal"];
        trace?: never;
    };
    "/api/v1/service-requests/{serviceRequestId}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create project from service request
         * @description Creates a project using the client and service from an existing service request. Admin can assign a manager; Manager is assigned to self.
         */
        post: operations["createProjectFromServiceRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch projects
         * @description Admin sees all projects; clients see own projects; other members see assigned or created projects.
         */
        get: operations["getProjects"];
        put?: never;
        /**
         * Create a project
         * @description Creates a project directly. Admin can assign a manager; Manager is assigned to self.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a project by id */
        get: operations["getProjectById"];
        /**
         * Update a project by id
         * @description Updates project details. Admin can reassign manager; Manager stays assigned to self.
         */
        put: operations["updateProjectById"];
        post?: never;
        /** Delete a project by id */
        delete: operations["deleteProjectById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch project tasks
         * @description Returns tasks for a project visible to the current member. Members receive only tasks assigned to them.
         */
        get: operations["getProjectTasks"];
        put?: never;
        /**
         * Create a project task
         * @description Creates a task in an accessible project. Only Admin and Manager members can create and assign tasks.
         */
        post: operations["createProjectTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch visible tasks
         * @description Returns tasks from accessible projects. Members receive only tasks assigned to them.
         */
        get: operations["getTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a task
         * @description Updates an accessible task. Members can update assigned tasks but cannot change task assignments.
         */
        put: operations["updateTaskById"];
        post?: never;
        /**
         * Delete a task
         * @description Deletes an accessible task. Only Admin and Manager members can delete tasks.
         */
        delete: operations["deleteTaskById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a service request by id
         * @description Requires serviceRequest:read permission in the active organization.
         */
        get: operations["getServiceRequestById"];
        /**
         * Update a service request by id
         * @description Requires serviceRequest:update permission in the active organization.
         */
        put: operations["updateServiceRequestById"];
        post?: never;
        /**
         * Delete a service request by id
         * @description Requires serviceRequest:delete permission in the active organization.
         */
        delete: operations["deleteServiceRequestById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example NEW
         * @enum {string}
         */
        LeadStatus: "NEW" | "QUALIFIED" | "IN_PROGRESS" | "DEAD";
        /**
         * @example CONTACT_FORM
         * @enum {string}
         */
        LeadSource: "CONTACT_FORM";
        /**
         * @example WEB_DEVELOPMENT
         * @enum {string}
         */
        ServiceInterest: "GOOGLE_ADS" | "SEO" | "WEB_DEVELOPMENT" | "MOBILE_APP_DEVELOPMENT" | "GENERAL_MARKETING" | "OTHER";
        /**
         * @example NEW
         * @enum {string}
         */
        ServiceRequestStatus: "NEW" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        /**
         * @example DRAFT
         * @enum {string}
         */
        ProposalStatus: "DRAFT" | "SENT" | "ACCEPTED";
        /**
         * @example UNPAID
         * @enum {string}
         */
        ProposalPaymentStatus: "UNPAID" | "PAID";
        /**
         * @example PLANNING
         * @enum {string}
         */
        ProjectStatus: "PLANNING" | "ACTIVE" | "ON_HOLD" | "COMPLETED" | "ARCHIVED";
        /**
         * @example MANAGER
         * @enum {string}
         */
        ProjectMemberRole: "MANAGER" | "MEMBER";
        /**
         * @default USD
         * @example USD
         * @enum {string}
         */
        ProjectCurrency: "USD" | "AED";
        /**
         * @example TODO
         * @enum {string}
         */
        TaskStatus: "TODO" | "IN_PROGRESS" | "IN_REVIEW" | "DONE";
        /**
         * @example MEDIUM
         * @enum {string}
         */
        TaskPriority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        AdminDashboardOverview: {
            /** @example 24 */
            totalLeads: number;
            /** @example 5 */
            newLeads: number;
            /** @example 12 */
            totalProjects: number;
            /** @example 7 */
            activeProjects: number;
            /** @example 48 */
            totalTasks: number;
            /** @example 18 */
            openTasks: number;
            /** @example 30 */
            completedTasks: number;
            /** @example 16 */
            totalServiceRequests: number;
            /** @example 4 */
            openServiceRequests: number;
        };
        LeadStatusDistribution: {
            /** @example 0 */
            NEW: number;
            /** @example 0 */
            QUALIFIED: number;
            /** @example 0 */
            IN_PROGRESS: number;
            /** @example 0 */
            DEAD: number;
        };
        TaskStatusDistribution: {
            /** @example 0 */
            TODO: number;
            /** @example 0 */
            IN_PROGRESS: number;
            /** @example 0 */
            IN_REVIEW: number;
            /** @example 0 */
            DONE: number;
        };
        AdminDashboardRecentLead: {
            /** @example clx0000000000000000000004 */
            id: string;
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName: string | null;
            status: components["schemas"]["LeadStatus"];
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            createdAt: string;
        };
        AdminDashboardAttentionTask: {
            /** @example clx0000000000000000000030 */
            id: string;
            /** @example clx0000000000000000000010 */
            projectId: string;
            /** @example Review client feedback */
            title: string;
            priority: components["schemas"]["TaskPriority"];
            /**
             * Format: date-time
             * @example 2026-07-08T06:30:00.000Z
             */
            dueDate: string | null;
            project: {
                /** @example FCOP Client Portal */
                name: string;
            };
        };
        /**
         * @example CLIENT
         * @enum {string}
         */
        OrganizationRole: "ADMIN" | "CLIENT" | "MANAGER" | "MEMBER";
        ApiResponse: {
            /** @example true */
            success: boolean;
            /** @example 200 */
            status: number;
            /** @example Health check passed. */
            message: string;
            data?: unknown;
            error?: {
                /** @example NOT_FOUND */
                code: string;
                details?: string;
            };
        };
        MeUser: {
            /** @example clx0000000000000000000000 */
            id: string;
            /** @example Akshay */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
        };
        /**
         * @description Role permission statements keyed by resource. The values are allowed CRUD or domain actions.
         * @example {
         *       "ac": [
         *         "read"
         *       ],
         *       "serviceRequest": [
         *         "create",
         *         "read"
         *       ],
         *       "project": [
         *         "read"
         *       ],
         *       "dashboard": [
         *         "read"
         *       ]
         *     }
         */
        PermissionStatements: {
            [key: string]: string[];
        };
        Me: {
            user: components["schemas"]["MeUser"];
            /** @example seed-org-fanatic-coders */
            organizationId: string;
            /** @example seed-member-client */
            memberId: string;
            role: components["schemas"]["OrganizationRole"];
            permissions: components["schemas"]["PermissionStatements"];
        };
        MeResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Me"];
        };
        User: {
            /** @example clx0000000000000000000000 */
            id: string;
            /** @example Akshay */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example true */
            emailVerified: boolean;
            /** @example https://example.com/avatar.png */
            image?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Session: {
            /** @example clx0000000000000000000001 */
            id: string;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            expiresAt: string;
            /** @example session-token */
            token: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
            /** @example 127.0.0.1 */
            ipAddress?: string | null;
            /** @example Mozilla/5.0 */
            userAgent?: string | null;
            /** @example clx0000000000000000000000 */
            userId: string;
        };
        Account: {
            /** @example clx0000000000000000000002 */
            id: string;
            /** @example akshay@example.com */
            accountId: string;
            /** @example credential */
            providerId: string;
            /** @example clx0000000000000000000000 */
            userId: string;
            accessToken?: string | null;
            refreshToken?: string | null;
            idToken?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            accessTokenExpiresAt?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            refreshTokenExpiresAt?: string | null;
            /** @example openid email profile */
            scope?: string | null;
            password?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Verification: {
            /** @example clx0000000000000000000003 */
            id: string;
            /** @example akshay@example.com */
            identifier: string;
            /** @example verification-token */
            value: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:45:00.000Z
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Lead: {
            /** @example clx0000000000000000000004 */
            id: string;
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status: components["schemas"]["LeadStatus"];
            source: components["schemas"]["LeadSource"];
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        CreateLeadRequest: {
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
        };
        UpdateLeadRequest: {
            /** @example Akshay Kumar */
            name?: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email?: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest?: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status?: components["schemas"]["LeadStatus"];
        };
        /**
         * @description Service-specific answers collected from the selected service template.
         * @example {
         *       "websiteUrl": "https://example.com",
         *       "targetKeywords": [
         *         "seo agency",
         *         "web development"
         *       ]
         *     }
         */
        ServiceRequestData: {
            [key: string]: unknown;
        };
        ServiceRequest: {
            /** @example clx0000000000000000000006 */
            id: string;
            /** @example clx0000000000000000000005 */
            clientId: string;
            service: components["schemas"]["ServiceInterest"];
            status: components["schemas"]["ServiceRequestStatus"];
            data?: components["schemas"]["ServiceRequestData"] | null;
            proposal?: components["schemas"]["Proposal"] | null;
            /** @description Linked project reference once this service request has been converted into a project. */
            project?: {
                /** @example clx0000000000000000000011 */
                id: string;
            } | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        CreateServiceRequestRequest: {
            service: components["schemas"]["ServiceInterest"];
            data?: components["schemas"]["ServiceRequestData"];
        };
        UpdateServiceRequestRequest: {
            status?: components["schemas"]["ServiceRequestStatus"];
            data?: components["schemas"]["ServiceRequestData"];
        };
        Proposal: {
            /** @example clx0000000000000000000020 */
            id: string;
            /** @example clx0000000000000000000006 */
            serviceRequestId: string;
            /** @example seed-member-manager */
            createdByMemberId: string;
            /** @example Design and develop the agreed business website. */
            description: string;
            /**
             * Format: decimal
             * @example 5000
             */
            amount: number;
            currency: components["schemas"]["ProjectCurrency"];
            status: components["schemas"]["ProposalStatus"];
            paymentStatus: components["schemas"]["ProposalPaymentStatus"];
            /**
             * Format: date-time
             * @example 2026-07-30T10:00:00.000Z
             */
            acceptedAt?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-30T10:05:00.000Z
             */
            paidAt?: string | null;
            /** @example in_1Example */
            stripeInvoiceId?: string | null;
            /** @example A1B2C3D4-0001 */
            stripeInvoiceNumber?: string | null;
            /**
             * Format: uri
             * @example https://invoice.stripe.com/i/example
             */
            stripeHostedInvoiceUrl?: string | null;
            /**
             * Format: uri
             * @example https://pay.stripe.com/invoice/example/pdf
             */
            stripeInvoicePdfUrl?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-30T09:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-07-30T10:05:00.000Z
             */
            updatedAt: string;
        };
        Payment: {
            /** @example clx0000000000000000000020 */
            id: string;
            /** @example clx0000000000000000000020 */
            proposalId: string;
            /** @example clx0000000000000000000006 */
            serviceRequestId: string;
            client: {
                /** @example clx0000000000000000000005 */
                id: string;
                /** @example Acme Ltd */
                name: string;
                /**
                 * Format: email
                 * @example billing@acme.example
                 */
                email: string;
            };
            /** @example Design and develop the agreed business website. */
            description: string;
            /** @example 5000.00 */
            amount: string;
            currency: components["schemas"]["ProjectCurrency"];
            status: components["schemas"]["ProposalPaymentStatus"];
            /** Format: date-time */
            paidAt?: string | null;
            /** @example in_1Example */
            stripeInvoiceId: string;
            /** @example A1B2C3D4-0001 */
            stripeInvoiceNumber?: string | null;
            /** Format: uri */
            stripeHostedInvoiceUrl?: string | null;
            /** Format: uri */
            stripeInvoicePdfUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProposalRequest: {
            /** @example Design and develop the agreed business website. */
            description: string;
            /** @example 5000 */
            amount: number;
            currency: components["schemas"]["ProjectCurrency"];
        };
        UpdateProposalRequest: {
            description?: string;
            amount?: number;
            currency?: components["schemas"]["ProjectCurrency"];
            status?: components["schemas"]["ProposalStatus"];
        };
        ProjectMember: {
            /** @example clx0000000000000000000011 */
            id: string;
            /** @example clx0000000000000000000010 */
            projectId: string;
            /** @example seed-member-manager */
            memberId: string;
            role: components["schemas"]["ProjectMemberRole"];
            /**
             * Format: date-time
             * @example 2026-07-21T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-07-21T06:30:00.000Z
             */
            updatedAt: string;
        };
        Project: {
            /** @example clx0000000000000000000010 */
            id: string;
            /** @example clx0000000000000000000005 */
            clientId: string;
            /** @example clx0000000000000000000006 */
            serviceRequestId?: string | null;
            /** @example seed-member-admin */
            createdByMemberId: string;
            /** @example Acme website redesign */
            name: string;
            /** @example Website redesign project created from the client service request. */
            description?: string | null;
            service: components["schemas"]["ServiceInterest"];
            status: components["schemas"]["ProjectStatus"];
            /**
             * Format: date-time
             * @example 2026-08-01T00:00:00.000Z
             */
            startDate?: string | null;
            /**
             * Format: date-time
             * @example 2026-09-15T00:00:00.000Z
             */
            endDate?: string | null;
            /**
             * Format: decimal
             * @example 25000
             */
            budgetAmount?: number | null;
            currency: components["schemas"]["ProjectCurrency"];
            /**
             * Format: date-time
             * @example 2026-07-21T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-07-21T06:30:00.000Z
             */
            updatedAt: string;
            memberProjects?: components["schemas"]["ProjectMember"][];
        };
        CreateProjectRequest: {
            /** @example clx0000000000000000000005 */
            clientId: string;
            /** @example clx0000000000000000000006 */
            serviceRequestId?: string;
            /**
             * @description Admin-only manager assignment. Managers are assigned to self by the backend.
             * @example seed-member-manager
             */
            managerMemberId?: string;
            /** @example Acme website redesign */
            name: string;
            /** @example Website redesign project created from discovery. */
            description?: string;
            service: components["schemas"]["ServiceInterest"];
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** @example 25000 */
            budgetAmount?: number;
            currency?: components["schemas"]["ProjectCurrency"];
        };
        CreateProjectFromServiceRequestRequest: {
            /**
             * @description Admin-only manager assignment. Managers are assigned to self by the backend.
             * @example seed-member-manager
             */
            managerMemberId?: string;
            /** @example Acme website redesign */
            name?: string;
            /** @example Project created from the accepted service request. */
            description?: string;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** @example 25000 */
            budgetAmount?: number;
            currency?: components["schemas"]["ProjectCurrency"];
        };
        UpdateProjectRequest: {
            /**
             * @description Admin-only manager reassignment. Managers are assigned to self by the backend.
             * @example seed-member-manager
             */
            managerMemberId?: string | null;
            name?: string;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            budgetAmount?: number | null;
            currency?: components["schemas"]["ProjectCurrency"];
        };
        TaskUser: {
            /** @example seed-user-member */
            id: string;
            /** @example Delivery Member */
            name: string;
            /**
             * Format: email
             * @example member@example.com
             */
            email: string;
            /**
             * Format: uri
             * @example https://example.com/avatar.png
             */
            image?: string | null;
        };
        TaskMember: {
            /** @example seed-member-member */
            id: string;
            /** @example seed-user-member */
            userId: string;
            /** @example seed-org-fanatic-coders */
            organizationId: string;
            role: components["schemas"]["OrganizationRole"];
            /**
             * Format: date-time
             * @example 2026-08-05T06:30:00.000Z
             */
            createdAt: string;
            user: components["schemas"]["TaskUser"];
        };
        TaskProjectReference: {
            /** @example clx0000000000000000000010 */
            id: string;
            /** @example Acme website redesign */
            name: string;
        };
        TaskAssignee: {
            /** @example clx0000000000000000000031 */
            id: string;
            /** @example clx0000000000000000000030 */
            taskId: string;
            /** @example clx0000000000000000000010 */
            projectId: string;
            /** @example seed-member-member */
            memberId: string;
            /**
             * Format: date-time
             * @example 2026-08-05T06:30:00.000Z
             */
            createdAt: string;
            member: components["schemas"]["TaskMember"];
        };
        Task: {
            /** @example clx0000000000000000000030 */
            id: string;
            /** @example clx0000000000000000000010 */
            projectId: string;
            /** @example seed-member-manager */
            createdByMemberId: string;
            /** @example Build homepage wireframe */
            title: string;
            /** @example Create the desktop and mobile homepage wireframes. */
            description?: string | null;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /**
             * Format: date-time
             * @example 2026-08-15T00:00:00.000Z
             */
            dueDate?: string | null;
            estimatedHours?: (string | number) | null;
            /**
             * Format: date-time
             * @example 2026-08-05T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-08-05T06:30:00.000Z
             */
            updatedAt: string;
            project: components["schemas"]["TaskProjectReference"];
            createdBy: components["schemas"]["TaskMember"];
            assignees: components["schemas"]["TaskAssignee"][];
        };
        CreateTaskRequest: {
            /** @example Build homepage wireframe */
            title: string;
            description?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /** Format: date-time */
            dueDate?: string;
            estimatedHours?: number;
            /** @default [] */
            assigneeMemberIds: string[];
        };
        UpdateTaskRequest: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /** Format: date-time */
            dueDate?: string | null;
            estimatedHours?: number | null;
            assigneeMemberIds?: string[];
        };
        TaskResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Task"];
        };
        TasksResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Task"][];
        };
        RequestPasswordResetRequest: {
            /**
             * Format: email
             * @example customer@example.com
             */
            email: string;
            /**
             * Format: uri
             * @description Optional frontend reset password page. Origin must be configured as a trusted frontend origin.
             * @example http://localhost:3000/reset-password
             */
            redirectTo?: string;
        };
        RequestPasswordResetResponse: components["schemas"]["ApiResponse"] & {
            /** @example null */
            data?: unknown;
            /** @example If an account exists for this email, a password reset link has been sent. */
            message?: string;
        };
        /**
         * @example CLIENT
         * @enum {string}
         */
        InviteMemberRole: "MANAGER" | "MEMBER" | "CLIENT";
        InviteMemberRequest: {
            /**
             * Format: email
             * @example client@example.com
             */
            email: string;
            role: components["schemas"]["InviteMemberRole"];
            serviceInterest?: components["schemas"]["ServiceInterest"];
            /**
             * @description Resend the invitation email if a pending invitation already exists.
             * @example true
             */
            resend?: boolean;
        };
        Invitation: {
            /** @example clx0000000000000000000005 */
            id: string;
            /**
             * Format: email
             * @example client@example.com
             */
            email: string;
            /** @example CLIENT */
            role: string;
            serviceInterest?: components["schemas"]["ServiceInterest"];
            /** @example seed-org-fanatic-coders */
            organizationId: string;
            /** @example seed-user-admin */
            inviterId: string;
            /** @example pending */
            status: string;
            /**
             * Format: date-time
             * @example 2026-07-08T06:30:00.000Z
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            createdAt?: string;
        };
        InvitationResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Invitation"];
        };
        LeadsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["PaginatedLeads"];
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 10 */
            pageSize: number;
            /** @example 24 */
            totalItems: number;
            /** @example 3 */
            totalPages: number;
        };
        Notification: {
            /** @example clx0000000000000000000040 */
            id: string;
            /** @example clx0000000000000000000002 */
            memberId: string;
            /** @example New task assigned */
            title: string;
            /** @example You were assigned to "Design homepage". */
            message: string;
            /** @example /dashboard/projects/clx0000000000000000000010 */
            link: string | null;
            /**
             * Format: date-time
             * @example null
             */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Notification"];
        };
        NotificationsResponse: components["schemas"]["ApiResponse"] & {
            data: {
                items: components["schemas"]["Notification"][];
                pagination: components["schemas"]["PaginationMeta"];
                /** @example 3 */
                unreadCount: number;
            };
        };
        MarkAllNotificationsReadResponse: components["schemas"]["ApiResponse"] & {
            data: {
                /** @example 3 */
                updatedCount: number;
            };
        };
        PaginatedLeads: {
            items: components["schemas"]["Lead"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        LeadResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Lead"];
        };
        LeadSubmissionResponse: components["schemas"]["ApiResponse"] & {
            data: {
                /** @enum {boolean} */
                accepted: true;
            };
        };
        ServiceRequestsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["ServiceRequest"][];
        };
        ServiceRequestResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["ServiceRequest"];
        };
        ProposalResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Proposal"];
        };
        PaymentsResponse: components["schemas"]["ApiResponse"] & {
            data: {
                items: components["schemas"]["Payment"][];
                pagination: components["schemas"]["PaginationMeta"];
            };
        };
        ProjectsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["PaginatedProjects"];
        };
        PaginatedProjects: {
            items: components["schemas"]["Project"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        ProjectResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Project"];
        };
        HealthResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["HealthData"];
        };
        HealthData: {
            /** @example ok */
            status: string;
            /** @example 42.5 */
            uptime: number;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description Authenticated user does not have the required permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        /** @example clx0000000000000000000004 */
        LeadId: string;
        /** @example clx0000000000000000000006 */
        ServiceRequestId: string;
        /** @example clx0000000000000000000006 */
        ServiceRequestProposalServiceRequestId: string;
        /** @example clx0000000000000000000006 */
        ServiceRequestProjectServiceRequestId: string;
        /** @example clx0000000000000000000010 */
        ProjectId: string;
        /** @example clx0000000000000000000010 */
        TaskProjectId: string;
        /** @example clx0000000000000000000030 */
        TaskId: string;
        /** @example clx0000000000000000000040 */
        NotificationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getPayments: {
        parameters: {
            query?: {
                /** @description Filter by payment status. */
                status?: components["schemas"]["ProposalPaymentStatus"];
                /** @description Filter by client name or email. */
                search?: string;
                /** @description One-based page number. */
                page?: number;
                /** @description Number of payments per page. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payments fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentsResponse"];
                };
            };
            /** @description Invalid payment filters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminDashboardOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch admin dashboard overview successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data: components["schemas"]["AdminDashboardOverview"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminDashboardLeadDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch admin lead status distribution successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data: components["schemas"]["LeadStatusDistribution"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminDashboardTaskDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch admin task status distribution successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data: components["schemas"]["TaskStatusDistribution"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminDashboardRecentLeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch recent admin dashboard leads successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data: components["schemas"]["AdminDashboardRecentLead"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminDashboardAttentionTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch admin dashboard attention tasks successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data: components["schemas"]["AdminDashboardAttentionTask"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsResponse"];
                };
            };
            /** @description Invalid notification filters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    markAllNotificationsAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All notifications marked as read. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkAllNotificationsReadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    markNotificationAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000040 */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked as read. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Notification was not found for the current member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Request accepted. The response does not reveal whether the email exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPasswordResetResponse"];
                };
            };
            /** @description Invalid email or redirect URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated user does not have an active organization member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Invitation created and invitation email queued/sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Invalid invitation payload or Better Auth rejected the invitation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description FCOP organization has not been bootstrapped. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getLeads: {
        parameters: {
            query?: {
                /** @description Filter by full or partial lead email. */
                email?: string;
                /** @description Filter by lead status. */
                status?: components["schemas"]["LeadStatus"];
                /** @description Filter by requested service type. */
                serviceType?: components["schemas"]["ServiceInterest"];
                /** @description One-based page number. */
                page?: number;
                /** @description Number of leads per page. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leads fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            /** @description Invalid lead filters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description Request received successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadSubmissionResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadRequest"];
            };
        };
        responses: {
            /** @description Lead updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getServiceRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service requests fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createServiceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceRequestRequest"];
            };
        };
        responses: {
            /** @description Service request created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Invalid service request payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Client profile has not been created. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getServiceRequestProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                serviceRequestId: components["parameters"]["ServiceRequestProposalServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request or proposal was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createServiceRequestProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                serviceRequestId: components["parameters"]["ServiceRequestProposalServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalRequest"];
            };
        };
        responses: {
            /** @description Proposal created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Invalid proposal payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description A proposal or project already exists for the service request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteServiceRequestProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                serviceRequestId: components["parameters"]["ServiceRequestProposalServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request or proposal was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Accepted proposal cannot be deleted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateServiceRequestProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                serviceRequestId: components["parameters"]["ServiceRequestProposalServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProposalRequest"];
            };
        };
        responses: {
            /** @description Proposal updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Invalid or empty proposal update. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Role is not allowed to perform the requested proposal transition or field update. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Service request or proposal was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Proposal state does not allow the requested update. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createProjectFromServiceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                serviceRequestId: components["parameters"]["ServiceRequestProjectServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectFromServiceRequestRequest"];
            };
        };
        responses: {
            /** @description Project created from service request successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Invalid project payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description A project already exists for this service request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: {
                /** @description Filter by full or partial project name. */
                name?: string;
                /** @description Filter by project status. */
                status?: components["schemas"]["ProjectStatus"];
                /** @description Filter by project service type. */
                serviceType?: components["schemas"]["ServiceInterest"];
                /** @description One-based page number. */
                page?: number;
                /** @description Number of projects per page. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Invalid project filters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Invalid project payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Client or service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000010 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000010 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Invalid project payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000010 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getProjectTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000010 */
                projectId: components["parameters"]["TaskProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksResponse"];
                };
            };
            /** @description Invalid project id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project was not found or is unavailable to the current member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createProjectTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000010 */
                projectId: components["parameters"]["TaskProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Invalid task payload or assignee. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project was not found or is unavailable to the current member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateTaskById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000030 */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Invalid or empty task update. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Task was not found or is unavailable to the current member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteTaskById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000030 */
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Invalid task id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Task was not found or is unavailable to the current member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service request fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceRequestRequest"];
            };
        };
        responses: {
            /** @description Service request updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            /** @description Invalid service request payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteServiceRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000006 */
                id: components["parameters"]["ServiceRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service request deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service request was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
