/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch all leads
         * @description Requires an authenticated user with ADMIN or MANAGER role.
         */
        get: operations["getLeads"];
        put?: never;
        /**
         * Create a lead
         * @description Creates a lead from an unauthenticated website form submission.
         */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a lead by id
         * @description Requires an authenticated user with ADMIN or MANAGER role.
         */
        get: operations["getLeadById"];
        /**
         * Update a lead by id
         * @description Requires an authenticated user with ADMIN or MANAGER role.
         */
        put: operations["updateLeadById"];
        post?: never;
        /**
         * Delete a lead by id
         * @description Requires an authenticated user with ADMIN or MANAGER role.
         */
        delete: operations["deleteLeadById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example CLIENT
         * @enum {string}
         */
        Role: "ADMIN" | "CLIENT" | "MANAGER" | "MEMBER";
        /**
         * @example NEW
         * @enum {string}
         */
        LeadStatus: "NEW" | "IN_PROGRESS" | "DEAD";
        /**
         * @example CONTACT_FORM
         * @enum {string}
         */
        LeadSource: "CONTACT_FORM";
        /**
         * @example WEB_DEVELOPMENT
         * @enum {string}
         */
        ServiceInterest: "GOOGLE_ADS" | "SEO" | "WEB_DEVELOPMENT" | "MOBILE_APP_DEVELOPMENT" | "GENERAL_MARKETING" | "OTHER";
        ApiResponse: {
            /** @example true */
            success: boolean;
            /** @example 200 */
            status: number;
            /** @example Health check passed. */
            message: string;
            data?: unknown;
            error?: {
                /** @example NOT_FOUND */
                code: string;
                details?: string;
            };
        };
        User: {
            /** @example clx0000000000000000000000 */
            id: string;
            /** @example Akshay */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example true */
            emailVerified: boolean;
            /** @example https://example.com/avatar.png */
            image?: string | null;
            role: components["schemas"]["Role"];
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Session: {
            /** @example clx0000000000000000000001 */
            id: string;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            expiresAt: string;
            /** @example session-token */
            token: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
            /** @example 127.0.0.1 */
            ipAddress?: string | null;
            /** @example Mozilla/5.0 */
            userAgent?: string | null;
            /** @example clx0000000000000000000000 */
            userId: string;
        };
        Account: {
            /** @example clx0000000000000000000002 */
            id: string;
            /** @example akshay@example.com */
            accountId: string;
            /** @example credential */
            providerId: string;
            /** @example clx0000000000000000000000 */
            userId: string;
            accessToken?: string | null;
            refreshToken?: string | null;
            idToken?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            accessTokenExpiresAt?: string | null;
            /**
             * Format: date-time
             * @example 2026-07-06T06:30:00.000Z
             */
            refreshTokenExpiresAt?: string | null;
            /** @example openid email profile */
            scope?: string | null;
            password?: string | null;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Verification: {
            /** @example clx0000000000000000000003 */
            id: string;
            /** @example akshay@example.com */
            identifier: string;
            /** @example verification-token */
            value: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:45:00.000Z
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        Lead: {
            /** @example clx0000000000000000000004 */
            id: string;
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status: components["schemas"]["LeadStatus"];
            source: components["schemas"]["LeadSource"];
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            updatedAt: string;
        };
        CreateLeadRequest: {
            /** @example Akshay Kumar */
            name: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
        };
        UpdateLeadRequest: {
            /** @example Akshay Kumar */
            name?: string;
            /**
             * Format: email
             * @example akshay@example.com
             */
            email?: string;
            /** @example Fanatic Coders */
            companyName?: string | null;
            serviceInterest?: components["schemas"]["ServiceInterest"];
            /** @example AED 10,000 - AED 25,000 */
            budgetRange?: string | null;
            status?: components["schemas"]["LeadStatus"];
        };
        LeadsResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Lead"][];
        };
        LeadResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["Lead"];
        };
        HealthResponse: components["schemas"]["ApiResponse"] & {
            data: components["schemas"]["HealthData"];
        };
        HealthData: {
            /** @example ok */
            status: string;
            /** @example 42.5 */
            uptime: number;
            /**
             * Format: date-time
             * @example 2026-06-29T06:30:00.000Z
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description Authenticated user does not have an allowed role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        /** @example clx0000000000000000000004 */
        LeadId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leads fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description Lead captured successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead fetched successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadRequest"];
            };
        };
        responses: {
            /** @description Lead updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Invalid lead payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteLeadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example clx0000000000000000000004 */
                id: components["parameters"]["LeadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lead was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
