import {
  siNextdotjs,
  siTypescript,
  siStripe,
  siPostgresql,
  siPrisma,
  siVercel,
  siReact,
  siClickhouse,
  siNodedotjs,
  siExpo,
  siSqlite,
  siGraphql,
  siFigma,
  siCss,
  siStorybook,
  siMapbox,
  siApachekafka,
  siGo,
  siKubernetes,
  siTrpc,
  type SimpleIcon,
} from 'simple-icons';

export const techIcons: Record<string, SimpleIcon> = {
  'Next.js': siNextdotjs,
  TypeScript: siTypescript,
  Stripe: siStripe,
  PostgreSQL: siPostgresql,
  Prisma: siPrisma,
  Vercel: siVercel,
  React: siReact,
  'React Native': siReact,
  ClickHouse: siClickhouse,
  'Node.js': siNodedotjs,
  Expo: siExpo,
  SQLite: siSqlite,
  GraphQL: siGraphql,
  Figma: siFigma,
  CSS: siCss,
  Storybook: siStorybook,
  Mapbox: siMapbox,
  Kafka: siApachekafka,
  Go: siGo,
  Kubernetes: siKubernetes,
  tRPC: siTrpc,
};
