import type { PortfolioProject } from "@/types"

export const projects: PortfolioProject[] = [
  {
    id: "northwind", title: "Northwind Commerce",
    description: "Headless storefront and checkout rebuild for a fast-growing retailer.",
    tags: ["E-Commerce", "Web"], client: "Northwind", year: "2026",
    industry: "Retail", duration: "10 weeks", services: ["E-Commerce", "Web Development"],
    stats: [
      { label: "conversion", value: "+38%", caption: "Higher checkout conversion", icon: "trendingUp" },
      { label: "load_time", value: "0.9s", caption: "Median page load", icon: "zap" },
      { label: "checkout_steps", value: "5 to 2", caption: "Checkout steps, down from five", icon: "listChecks" },
      { label: "uptime_sale", value: "100%", caption: "Uptime through peak sale", icon: "shieldCheck" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=720&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&h=600&fit=crop"],
    overview: "Northwind had outgrown its old monolith. Pages were slow, the checkout leaked customers, and every change took weeks. We rebuilt the storefront headless and reworked the path to purchase.",
    sections: [
      { heading: "Challenge", body: "Peak-season traffic pushed load times past four seconds and the checkout dropped one in three carts. The catalog was large and changed daily, so caching had to be smart rather than blunt, and the team needed to ship updates without a full release." },
      { heading: "Approach", body: "We moved to a headless storefront with edge caching keyed to the catalog, then rebuilt the checkout around two steps instead of five. Inventory, payments, and tax were integrated so stock and pricing stayed correct under load." },
      { heading: "Result", body: "Pages now load under a second and conversion rose 38 percent. The store held 100 percent uptime through its first peak sale, and the team ships catalog changes the same day instead of waiting on a release." },
    ],
    approach: [
      { title: "Replatform", duration: "~3 weeks", desc: "Rebuilt the storefront from scratch so pages load fast and stay fast under load." },
      { title: "Checkout", duration: "~2 weeks", desc: "Cut the checkout from five steps to two and added one-tap express payment." },
      { title: "Edge caching", duration: "~2 weeks", desc: "Cached pages at the edge and refreshed only the product that changed." },
      { title: "Integrations", duration: "~3 weeks", desc: "Wired inventory, payments, and tax together so stock and prices stay correct." },
    ],
    tech: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Vercel"],
    quote: { text: "They rebuilt our store in ten weeks and the numbers moved immediately. Checkout finally just works, and we ship changes ourselves now.", author: "Dana Ng", role: "VP Engineering, Northwind" },
  },
  {
    id: "pulse", title: "Pulse Analytics",
    description: "Real-time dashboard SaaS with sub-second queries over billions of rows.",
    tags: ["SaaS", "Web"], client: "Pulse", year: "2025",
    industry: "SaaS Analytics", duration: "14 weeks", services: ["Web Development", "Cloud Solutions"],
    stats: [
      { label: "query_p95", value: "120ms", caption: "Query time at p95", icon: "gauge" },
      { label: "MRR", value: "+2.1x", caption: "Monthly recurring revenue", icon: "trendingUp" },
      { label: "rows", value: "4.2B", caption: "Rows queried live", icon: "database" },
      { label: "churn", value: "-31%", caption: "Lower customer churn", icon: "trendingDown" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=720&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1543286386-713bdd548da4?w=900&h=600&fit=crop"],
    overview: "Pulse sells live analytics, so speed is the product. Their early build slowed to a crawl as data grew. We rearchitected the query path to stay fast at scale.",
    sections: [
      { heading: "Challenge", body: "Dashboards queried billions of rows and latency climbed with every new customer. Users felt the lag, and churn was starting to track it. The old row store could not keep up with the analytical workload." },
      { heading: "Approach", body: "We added a columnar store, pre-aggregated the heavy queries, and pushed rendering to the edge. Every query path got a p95 budget and a trace, so a regression surfaced in CI before it reached a customer." },
      { heading: "Result", body: "Query p95 settled at 120 milliseconds and held as data passed four billion rows. With the product fast again, monthly revenue more than doubled and churn dropped 31 percent." },
    ],
    approach: [
      { title: "Columnar store", duration: "~5 weeks", desc: "Moved the heavy queries to a column store and pre-built the slow ones." },
      { title: "Latency budget", duration: "~3 weeks", desc: "Set a speed limit for every query and made the build fail if it slipped." },
      { title: "Edge render", duration: "~3 weeks", desc: "Rendered the dashboard shell at the edge so the first screen shows instantly." },
      { title: "Tracing", duration: "~3 weeks", desc: "Traced every query so a slowdown shows up before a customer feels it." },
    ],
    tech: ["React", "ClickHouse", "Node.js", "WebSocket", "AWS"],
    quote: { text: "Speed is our product, and they treated it that way. The query budgets they set still hold two years later as we have grown.", author: "Marcus Bell", role: "CTO, Pulse" },
  },
  {
    id: "wander", title: "Wander",
    description: "Cross-platform travel app with offline itineraries and live sync.",
    tags: ["Mobile"], client: "Wander", year: "2025",
    industry: "Travel", duration: "12 weeks", services: ["Mobile Apps", "UI/UX Design"],
    stats: [
      { label: "rating", value: "4.9", caption: "App store rating", icon: "star" },
      { label: "installs", value: "250k+", caption: "Installs and counting", icon: "download" },
      { label: "offline_use", value: "63%", caption: "Sessions used offline", icon: "wifiOff" },
      { label: "crash_free", value: "99.8%", caption: "Crash-free sessions", icon: "shieldCheck" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&h=720&fit=crop",
    overview: "Wander needed one app for iOS and Android that worked without signal. Travelers plan offline and sync when they land, so the data model had to handle both.",
    sections: [
      { heading: "Challenge", body: "Itineraries had to be editable with no connection and merge cleanly once back online, without losing a traveler's changes. Two app stores from one team meant the codebase had to stay shared without feeling cross-platform." },
      { heading: "Approach", body: "We built on a cross-platform codebase with a local-first store and conflict-aware sync. Maps, offline tiles, and push were wired in from the start, and the UI was tuned per platform so it felt native on both." },
      { heading: "Result", body: "Wander shipped to both stores from one codebase, holds a 4.9 rating, and has passed 250,000 installs. Almost two thirds of sessions happen offline, and the app stays crash free 99.8 percent of the time." },
    ],
    approach: [
      { title: "Local-first", duration: "~4 weeks", desc: "Built the app to work offline first, then sync cleanly when signal returns." },
      { title: "Offline", duration: "~3 weeks", desc: "Bundled maps and itinerary editing so travelers can plan with no connection." },
      { title: "One codebase", duration: "~3 weeks", desc: "Shipped iOS and Android from one codebase, tuned to feel native on each." },
      { title: "Telemetry", duration: "~2 weeks", desc: "Added push, deep links, and analytics from the first build." },
    ],
    tech: ["React Native", "Expo", "SQLite", "GraphQL"],
    quote: { text: "Offline was the hard part and they nailed it. Travelers edit plans on a plane and everything is just there when they land.", author: "Priya Shah", role: "Founder, Wander" },
  },
  {
    id: "forge", title: "Forge Identity",
    description: "Brand system and design language for a developer-tools company.",
    tags: ["Branding"], client: "Forge", year: "2025",
    industry: "Developer Tools", duration: "6 weeks", services: ["Brand Identity", "UI/UX Design"],
    stats: [
      { label: "recall", value: "+64%", caption: "Higher brand recall", icon: "trendingUp" },
      { label: "assets", value: "120", caption: "Documented brand assets", icon: "layers" },
      { label: "ship_time", value: "-40%", caption: "Faster to ship a page", icon: "zap" },
      { label: "tokens", value: "180", caption: "Design tokens shipped", icon: "palette" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=720&fit=crop",
    overview: "Forge had a strong product and an inconsistent look. We built a brand system that holds together across a site, docs, and a growing set of tools.",
    sections: [
      { heading: "Challenge", body: "Every surface looked slightly different and the team had no shared source for type, color, or spacing. New pages drifted from the brand because matching it by eye was the only option." },
      { heading: "Approach", body: "We designed a flexible mark, set the system as tokens, and documented rules a developer and a designer could both pull from. Components shipped with the tokens baked in so the brand traveled with the code." },
      { heading: "Result", body: "Brand recall rose 64 percent in user testing, and 120 documented assets keep new pages on brand without hand holding. The team ships branded pages 40 percent faster." },
    ],
    approach: [
      { title: "The mark", duration: "~2 weeks", desc: "Designed a logo that stays sharp at every size and on every surface." },
      { title: "Tokens", duration: "~2 weeks", desc: "Turned type, color, and spacing into 180 reusable design tokens." },
      { title: "Components", duration: "~1 week", desc: "Shipped UI components with the tokens already built in." },
      { title: "Guidelines", duration: "~1 week", desc: "Wrote one guide a designer and a developer can both follow." },
    ],
    tech: ["Figma", "Tokens Studio", "CSS", "Storybook"],
    quote: { text: "Our product always shipped fast, our brand never kept up. Now new pages look right by default and we stopped arguing about hex codes.", author: "Leah Cohen", role: "Head of Product, Forge" },
  },
  {
    id: "lumen", title: "Lumen Health",
    description: "HIPAA-ready patient portal with scheduling and secure messaging.",
    tags: ["Web", "SaaS"], client: "Lumen", year: "2026",
    industry: "HealthTech", duration: "16 weeks", services: ["Web Development", "UI/UX Design"],
    stats: [
      { label: "uptime", value: "99.98%", caption: "Platform uptime", icon: "activity" },
      { label: "NPS", value: "72", caption: "Patient NPS", icon: "heart" },
      { label: "audit_pass", value: "1st try", caption: "Security audit passed", icon: "shieldCheck" },
      { label: "no_show", value: "-22%", caption: "Fewer appointment no-shows", icon: "trendingDown" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&h=720&fit=crop",
    overview: "Lumen needed a patient portal that met HIPAA without feeling clinical. Scheduling and secure messaging had to be simple for patients of every age.",
    sections: [
      { heading: "Challenge", body: "Health data raises the bar on security and accessibility, and the audience spans a wide range of comfort with technology. The portal had to pass a security review and still feel easy for a first-time user." },
      { heading: "Approach", body: "We built encrypted messaging and scheduling on audited infrastructure, then designed flows that stay clear under stress and meet WCAG AA. Every screen was tested with real patients before launch." },
      { heading: "Result", body: "The portal passed its security review on the first pass, holds 99.98 percent uptime, and earns an NPS of 72. Appointment no-shows dropped 22 percent after launch." },
    ],
    approach: [
      { title: "Secure core", duration: "~6 weeks", desc: "Built encrypted messaging and scheduling on audited, HIPAA-ready infrastructure." },
      { title: "Accessible flows", duration: "~4 weeks", desc: "Designed flows that meet WCAG AA and stay clear when people are stressed." },
      { title: "Patient testing", duration: "~3 weeks", desc: "Tested every screen with real patients before launch." },
      { title: "Compliance", duration: "~3 weeks", desc: "Set up audit logs and access controls to pass the security review." },
    ],
    tech: ["Next.js", "tRPC", "PostgreSQL", "AWS", "Auth"],
    quote: { text: "They shipped on time and passed our security review on the first pass. We trusted them with the hard parts and they delivered.", author: "Dr. Emily Watson", role: "Product Lead, Lumen Health" },
  },
  {
    id: "atlas", title: "Atlas Logistics",
    description: "Fleet tracking platform with live maps and route optimization.",
    tags: ["Web", "Mobile"], client: "Atlas", year: "2026",
    industry: "Logistics", duration: "14 weeks", services: ["Web Development", "Cloud Solutions"],
    stats: [
      { label: "fuel_saved", value: "18%", caption: "Less fuel used", icon: "fuel" },
      { label: "fleets", value: "340", caption: "Fleets on the platform", icon: "truck" },
      { label: "vehicles", value: "12k", caption: "Vehicles tracked live", icon: "mapPin" },
      { label: "route_calc", value: "real-time", caption: "Route recalculation", icon: "navigation" },
    ],
    imageUrl: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=1200&h=720&fit=crop",
    overview: "Atlas manages fleets that move all day. They needed live tracking and routing that cut fuel without adding work for drivers.",
    sections: [
      { heading: "Challenge", body: "Thousands of vehicles report position constantly, and routes have to recompute in real time as traffic and orders change. The driver app had to stay simple so it did not slow anyone down." },
      { heading: "Approach", body: "We built live maps on a streaming pipeline and a routing engine tuned for fuel and time. The driver app kept instructions to one clear action at a time, and dispatch saw the whole fleet on one map." },
      { heading: "Result", body: "Atlas cut fuel use 18 percent across 340 fleets and 12,000 vehicles, while drivers kept the same routine. Routes recompute in real time as conditions change." },
    ],
    approach: [
      { title: "Live pipeline", duration: "~5 weeks", desc: "Streamed every vehicle's position through a real-time pipeline." },
      { title: "Routing engine", duration: "~4 weeks", desc: "Built routing that picks the cheapest, fastest path as conditions change." },
      { title: "Driver app", duration: "~3 weeks", desc: "Kept the driver app to one clear instruction at a time." },
      { title: "Dispatch view", duration: "~2 weeks", desc: "Put the whole fleet on a single live map for dispatch." },
    ],
    tech: ["React", "Mapbox", "Kafka", "Go", "Kubernetes"],
    quote: { text: "Eighteen percent less fuel across the whole fleet, and our drivers did not have to change a thing. That is the result that mattered to us.", author: "Tom Reed", role: "Operations Director, Atlas" },
  },
]

export function getProject(id: string): PortfolioProject | undefined {
  return projects.find((p) => p.id === id)
}
